"""Tests for scripts/build_confusion_weights.py (OCR confusion-cost learning).

Toy alignment fixtures plus a subprocess determinism/acceptance run on a
synthetic CSV: no network, no DB, pure stdlib + pytest. Also pins the shipped
config/ocr_confusion.json artifact (generated by the same script).
"""

import importlib.util
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

SCRIPT = REPO_ROOT / "scripts" / "build_confusion_weights.py"
_spec = importlib.util.spec_from_file_location("build_confusion_weights", SCRIPT)
bcw = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(bcw)

from retrieval.ocr_variants import derive_confusion_classes, load_confusion, skeleton

ARTIFACT_KEYS = {
    "version",
    "generated",
    "sources",
    "classes",
    "sub_costs",
    "pair_costs",
    "default_sub_cost",
    "indel_cost",
}


# ---------------------------------------------------------------- normalization


def test_normalize_token_strips_edge_punctuation_and_lowercases():
    assert bcw.normalize_token("FUER#") == "fuer"
    assert bcw.normalize_token('"FUHR,"') == "fuhr"
    assert bcw.normalize_token("  Dogreo#") == "dogreo"
    assert bcw.normalize_token("G.") == "g"
    # interior punctuation survives (only the edges are stripped)
    assert bcw.normalize_token("i(his") == "i(his"
    assert bcw.normalize_token("***") == ""


# ---------------------------------------------------------------- alignment counts


def test_alignment_counts_single_char_substitutions():
    subs, merges, n_ins, n_del = bcw.count_pair_confusions("reoeivod", "received")
    assert subs == Counter({"c|o": 1, "e|o": 1})
    assert merges == Counter()
    assert (n_ins, n_del) == (0, 0)

    subs, merges, n_ins, n_del = bcw.count_pair_confusions("sane", "some")
    assert subs == Counter({"a|o": 1, "m|n": 1})
    assert merges == Counter()
    assert (n_ins, n_del) == (0, 0)


def test_alignment_counts_two_gram_merge_both_directions():
    # typed m read as rn (embedded has the 2-gram)
    subs, merges, n_ins, n_del = bcw.count_pair_confusions("rnodern", "modern")
    assert merges == Counter({"rn|m": 1})
    assert subs == Counter()
    assert (n_ins, n_del) == (0, 0)

    # typed rn read as m (accepted has the 2-gram) collapses to the same key
    subs, merges, n_ins, n_del = bcw.count_pair_confusions("modern", "rnodern")
    assert merges == Counter({"rn|m": 1})
    assert subs == Counter()
    assert (n_ins, n_del) == (0, 0)


def test_alignment_counts_bare_indels():
    subs, merges, n_ins, n_del = bcw.count_pair_confusions("bentle", "bentley")
    assert (subs, merges) == (Counter(), Counter())
    assert (n_ins, n_del) == (1, 0)

    subs, merges, n_ins, n_del = bcw.count_pair_confusions("bentleyy", "bentley")
    assert (subs, merges) == (Counter(), Counter())
    assert (n_ins, n_del) == (0, 1)


def test_alignment_ignores_punctuation_substitutions():
    # curly vs straight apostrophe is not a learnable OCR char confusion
    subs, merges, n_ins, n_del = bcw.count_pair_confusions("master’s", "master's")
    assert subs == Counter()
    assert merges == Counter()
    assert (n_ins, n_del) == (0, 0)


# ---------------------------------------------------------------- cost merge


def test_interpolate_costs_prior_merge():
    counts = Counter({"e|o": 10, "x|z": 7, "q|w": 3})
    priors = {"e|o": 0.3, "a|b": 0.4}
    out = bcw.interpolate_costs(counts, priors)
    # observed prior interpolates toward 0.15 by share (10/10 -> the floor)
    assert out["e|o"] == 0.15
    # new learned pair enters from base 0.5: 0.5 - (0.5 - 0.15) * 7/10
    assert out["x|z"] == 0.255
    assert out["x|z"] <= 0.5
    # below MIN_OBSERVED: dropped
    assert "q|w" not in out
    # unobserved prior keeps its base cost
    assert out["a|b"] == 0.4


def test_interpolate_costs_no_observations_keeps_priors():
    priors = {"e|o": 0.3}
    assert bcw.interpolate_costs(Counter({"x|z": 2}), priors) == {"e|o": 0.3}


# ---------------------------------------------------------------- classes


def test_class_size_cap_blocks_late_cheap_merges():
    sub_costs = {"a|b": 0.1, "b|c": 0.2, "c|d": 0.25, "d|e": 0.3, "e|f": 0.3}
    classes = derive_confusion_classes(sub_costs)
    # a-b-c-d fills the 4-member cap; d|e is blocked, e|f forms its own class
    assert classes == [["a", "b", "c", "d"], ["e", "f"]]


# ---------------------------------------------------------------- end-to-end


TOY_ROWS = (
    [("reoeivod", "received")] * 6
    + [("rnodern", "modern")] * 5
    + [("FUER#", '"FUHR,"')]
    + [("G.", "Gi"), ("same", "same")]  # skipped: <2 alnum chars / equal
)


def _write_toy_csv(path: Path) -> None:
    lines = ["page,embedded_token,accepted_token"]
    for emb, acc in TOY_ROWS:
        acc = acc.replace('"', '""')
        lines.append(f'1,{emb},"{acc}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _run_script(csv_path: Path, out_path: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--csv", str(csv_path), "--out", str(out_path)],
        capture_output=True,
        text=True,
    )


def test_script_deterministic_and_acceptance(tmp_path):
    csv_path = tmp_path / "toy_pairs.csv"
    _write_toy_csv(csv_path)
    out1 = tmp_path / "run1.json"
    out2 = tmp_path / "run2.json"

    res1 = _run_script(csv_path, out1)
    assert res1.returncode == 0, res1.stderr
    assert "Acceptance OK" in res1.stdout
    assert "Pairs used: 12" in res1.stdout  # 6 + 5 + fuer/fuhr; 2 rows skipped

    res2 = _run_script(csv_path, out2)
    assert res2.returncode == 0, res2.stderr

    # two runs on identical inputs are byte-identical
    assert out1.read_bytes() == out2.read_bytes()

    artifact = json.loads(out1.read_text(encoding="utf-8"))
    assert set(artifact.keys()) == ARTIFACT_KEYS
    assert artifact["version"] == "ocr_confusion_v1"
    assert artifact["sources"] == [str(csv_path)]
    assert artifact["default_sub_cost"] == 1.0
    assert artifact["indel_cost"] == 0.8

    # learned costs: both observed subs share the max count -> the floor;
    # the observed prior pair rn|m interpolates from 0.35 to the floor too
    assert artifact["sub_costs"]["e|o"] == 0.15
    assert artifact["sub_costs"]["c|o"] == 0.15
    assert artifact["pair_costs"]["rn|m"] == 0.15
    # fuer/fuhr appears once (< MIN_OBSERVED): e|h keeps its prior base
    assert artifact["sub_costs"]["e|h"] == 0.35

    # the acceptance invariant holds when reloaded through the module
    conf = load_confusion(str(out1))
    assert skeleton("fuhr", conf) == skeleton("fuer", conf) != ""


def test_shipped_artifact_valid_and_accepts_fuhr_fuer():
    shipped = REPO_ROOT / "config" / "ocr_confusion.json"
    assert shipped.is_file(), "run scripts/build_confusion_weights.py to generate it"
    artifact = json.loads(shipped.read_text(encoding="utf-8"))
    assert set(artifact.keys()) == ARTIFACT_KEYS
    assert artifact["version"] == "ocr_confusion_v1"
    assert artifact["sub_costs"]["e|h"] <= 0.35  # within the class threshold

    conf = load_confusion(str(shipped))
    assert skeleton("fuhr", conf) == skeleton("fuer", conf) != ""
    # e and h share a confusion class in the shipped artifact
    cls_by_char = {ch: cls[0] for cls in artifact["classes"] for ch in cls}
    assert cls_by_char.get("e") is not None
    assert cls_by_char.get("e") == cls_by_char.get("h")
